"""
Analyze the DeepAgents example-workflow screen recording with Gemini (Vertex AI),
mirroring the methodology used for the Vanguard video (analyze_vanguard_video.py).

Two departures from that pattern:

1. **Inline bytes instead of GCS** — the recording is 13 MB, under Gemini's inline
   cap, so the video is passed as `types.Part.from_bytes`. GCS fallback only if the
   inline call is rejected outright.
2. **Fast-model-first chain** — gemini-2.5-flash → gemini-2.5-pro → gemini-1.5-pro.

Produces:
  1. vanguard_video/deepagents_video_analysis.md   — full summarization
  2. vanguard_video/deepagents_agent_manifest.json — structured extraction:
     agents, planning artifacts, file artifacts, UI grammar, steering moments,
     and the step-by-step way a dashboard gets generated by an agent.
"""

import json
import os
from pathlib import Path

from google import genai
from google.genai import types

PROJECT_ID = "ultimate3dreconstructionstack"
LOCATION = "us-central1"
VIDEO_PATH = Path("vanguard_video/deepAgents-example-workflow.mov")
GCS_FALLBACK_URI = "gs://meghdoot-artifacts/video_analysis/deepAgents-example-workflow.mov"

OUT_MD = "vanguard_video/deepagents_video_analysis.md"
OUT_MANIFEST = "vanguard_video/deepagents_agent_manifest.json"

MODELS_TO_TRY = [
    "gemini-2.5-flash",
    "gemini-2.5-pro",
    "gemini-1.5-pro",
]

SUMMARIZATION_PROMPT = """You are an expert agentic-AI workflow analyst. Analyze the \
attached screen recording of a DeepAgents-style workflow (an agentic AI framework \
running in a UI). Perform an in-depth video-to-summarization analysis with these \
sections:

1. EXECUTIVE SUMMARY & OVERVIEW — what the recording demonstrates, and the workflow arc.
2. STEP-BY-STEP TIMELINE & ACTION BREAKDOWN — chronological beats with approximate \
timestamps (MM:SS): every agent creation, tool call, artifact write, and human action.
3. AGENT INVENTORY — for EVERY agent visible: its name, its role, the tools it calls, \
any sub-agents it spawns, and how its output manifests (chat, file, dashboard).
4. PLANNING & ARTIFACT ANALYSIS — the plan/todo list (its shape, how items tick off), \
the virtual file system artifacts (what gets written where, in what order), and any \
hand-off between agents.
5. HUMAN STEERING MOMENTS — every interruption, redirection, or approval by the human \
operator, timestamped, with what changed because of it.
6. UI COMPONENT & LAYOUT ANALYSIS — panel positions (left/right/docked), colours, \
list styles, streaming/working states, and how "the agent is building something" is \
made visually legible.
7. TECHNICAL OBSERVATIONS — how the workflow composes planning + sub-agents + file \
artifacts into one legible run, and what a financial trading-floor analogue should \
copy from it.
"""

MANIFEST_PROMPT = """You are producing a precise structured manifest from the attached \
screen recording of a DeepAgents-style agentic workflow.

Return ONLY valid JSON with exactly this shape:

{
  "agents": [
    {
      "id": "short-slug",
      "name": "agent name as shown",
      "role": "what it does",
      "tools": ["tool names it calls"],
      "subagents_spawned": ["ids of sub-agents it creates"],
      "output_manifests_as": "chat | file artifact | dashboard | other"
    }
  ],
  "planning_artifacts": {
    "exists": true,
    "shape": "how the plan/todo list is laid out",
    "lifecycle": ["ordered description of plan states over the run"]
  },
  "file_artifacts": [
    { "name": "artifact name", "written_at_step": "when", "content_summary": "what it holds" }
  ],
  "ui_grammar": {
    "panel_positions": "where chat / plan / files / tool streams sit",
    "colors": ["dominant accent colors"],
    "list_styles": "how lists/checks render",
    "working_states": "how 'the agent is building' is made visually legible"
  },
  "steering_moments": [
    { "timestamp": "MM:SS", "human_action": "what the human did", "effect": "what changed" }
  ],
  "dashboard_built_steps": ["ordered steps by which an agent builds/creates a dashboard \
or screen in this workflow"],
  "model": null,
  "source": null
}

Every field must be grounded in what is actually visible at some timestamp in the \
recording — do not extrapolate capabilities the video does not show. Set "model" and \
"source" to null; the caller fills them.
"""


def get_client():
    return genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)


def generate_with_fallback(client, contents, config):
    last_err = None
    for model_name in MODELS_TO_TRY:
        try:
            print(f"  -> trying model: {model_name}")
            resp = client.models.generate_content(
                model=model_name,
                contents=contents,
                config=config,
            )
            return model_name, resp
        except Exception as e:  # noqa: BLE001
            last_err = e
            print(f"  -> {model_name} failed: {e}")
    raise RuntimeError(f"All Gemini models failed. Last error: {last_err}")


def parse_json_block(text):
    text = text.strip()
    if text.startswith("```"):
        lines = [l for l in text.splitlines() if not l.strip().startswith("```")]
        text = "\n".join(lines).strip()
    return json.loads(text)


def salvage_json(text):
    for cut in range(len(text), 0, -1):
        try:
            return json.loads(text[:cut])
        except Exception:
            continue
    raise ValueError("Could not salvage any JSON from model output")


def video_part() -> types.Part:
    data = VIDEO_PATH.read_bytes()
    print(f"Loaded video inline: {VIDEO_PATH} ({len(data):,} bytes)")
    return types.Part.from_bytes(data=data, mime_type="video/quicktime")


def main():
    client = get_client()
    print(f"Initialized Gemini client (project={PROJECT_ID}, location={LOCATION})")

    part = video_part()

    # 1) Full summarization
    if os.path.exists(OUT_MD) and os.path.getsize(OUT_MD) > 1000:
        print(f"Skipping summarization (already present: {OUT_MD})")
    else:
        print("Running full summarization...")
        model_used, resp = generate_with_fallback(
            client,
            contents=[part, SUMMARIZATION_PROMPT],
            config=types.GenerateContentConfig(temperature=0.2, max_output_tokens=8192),
        )
        md = (
            f"# DeepAgents Example Workflow — Video Analysis\n\n"
            f"_Model: {model_used} | Video: {VIDEO_PATH} (inline)_\n\n---\n\n{resp.text}"
        )
        with open(OUT_MD, "w") as f:
            f.write(md)
        print(f"Saved summarization to {OUT_MD}")

    # 2) Structured agent manifest
    print("Extracting structured agent manifest...")
    model_used2, resp2 = generate_with_fallback(
        client,
        contents=[part, MANIFEST_PROMPT],
        config=types.GenerateContentConfig(
            temperature=0.0,
            max_output_tokens=32768,
            response_mime_type="application/json",
        ),
    )
    raw = resp2.text
    try:
        data = parse_json_block(raw)
    except Exception:
        print("WARNING: raw JSON parse failed; salvaging prefix...")
        data = salvage_json(raw)

    data["model"] = model_used2
    data["source"] = str(VIDEO_PATH)
    with open(OUT_MANIFEST, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Saved agent manifest to {OUT_MANIFEST}")

    # Quick console digest
    agents = data.get("agents", [])
    steering = data.get("steering_moments", [])
    steps = data.get("dashboard_built_steps", [])
    print(f"\nDigest: {len(agents)} agents · {len(steering)} steering moments · "
          f"{len(steps)} dashboard-build steps")
    for a in agents:
        print(f"  - {a.get('name')}: {a.get('role')} (tools: {', '.join(a.get('tools', [])[:3])})")


if __name__ == "__main__":
    main()
