import "server-only";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { unstable_cache } from "next/cache";
import type { ForecastPayload } from "@/lib/demo/data";

/**
 * Server-side data access for the demo data snapshots.
 *
 * This replaces the previous pattern — a `useEffect` firing `fetch('/api/demo/…')`
 * with `cache: "no-store"` — which meant: no SSR data, an empty first paint, a
 * client waterfall, and a cache defeated on every request.
 *
 * Now the JSON is read on the server, memoised across requests with
 * `unstable_cache`, and handed to Server Components. Repeated loads never touch
 * the filesystem, and the browser never makes a data request at all.
 *
 * The same `readFile` path resolution is kept from the route handlers: cwd is the
 * app dir locally and the traced output dir on Vercel.
 */

const FORECAST_FILES: Record<string, string> = {
  aave: "aave_forecast.json",
  morpho: "morpho_forecast.json",
  lido: "lido_forecast.json",
  rocketpool: "rocketpool_forecast.json",
  polymarket: "polymarket_forecast.json",
  hyperliquid: "hyperliquid_forecast.json",
  uniswap: "uniswap_forecast.json",
};

export const FORECAST_KEYS = Object.keys(FORECAST_FILES);

function candidatePaths(...segments: string[]): string[] {
  return [
    path.resolve(process.cwd(), ...segments),
    path.resolve(process.cwd(), "..", "..", ...segments),
  ];
}

async function readJson<T>(segments: string[]): Promise<T | null> {
  for (const candidate of candidatePaths(...segments)) {
    try {
      return JSON.parse(await readFile(candidate, "utf8")) as T;
    } catch {
      // try the next candidate
    }
  }
  return null;
}

/**
 * Forecasts are regenerated by a batch job, not per request, so a one-hour cache
 * is well inside the data's real freshness and removes the read entirely from
 * the hot path.
 */
const readForecast = unstable_cache(
  async (key: string): Promise<ForecastPayload | null> => {
    const file = FORECAST_FILES[key];
    if (!file) return null;
    return readJson<ForecastPayload>(["data", "forecasts", file]);
  },
  ["demo-forecast"],
  { revalidate: 3600, tags: ["demo-forecast"] },
);

export async function getForecast(key: string): Promise<ForecastPayload | null> {
  if (!FORECAST_FILES[key]) return null;
  return readForecast(key);
}

/** All forecasts keyed by protocol — one server pass instead of N client fetches. */
export async function getAllForecasts(): Promise<Record<string, ForecastPayload>> {
  const entries = await Promise.all(
    FORECAST_KEYS.map(async (key) => [key, await readForecast(key)] as const),
  );
  const out: Record<string, ForecastPayload> = {};
  for (const [key, payload] of entries) {
    if (payload) out[key] = payload;
  }
  return out;
}

export interface MarketSummary {
  generatedAt: string;
  protocolsTotal: number;
  categories: number;
  sections: { id: string; label: string; protocolCount: number }[];
  sourceEndpoints: string[];
}

interface TaxonomyShape {
  metadata?: {
    generatedAt?: string;
    counts?: { protocolsTotal?: number; categories?: number };
    sources?: { apiEndpoints?: string[] };
  };
  metricsSections?: Record<string, { label?: string; protocolCount?: number }>;
}

const readMarket = unstable_cache(
  async (): Promise<MarketSummary | null> => {
    const taxonomy = await readJson<TaxonomyShape>([
      "data",
      "defillama_metrics",
      "defillama_metrics_taxonomy.json",
    ]);
    if (!taxonomy) return null;

    const meta = taxonomy.metadata ?? {};
    return {
      generatedAt: meta.generatedAt ?? "",
      protocolsTotal: meta.counts?.protocolsTotal ?? 0,
      categories: meta.counts?.categories ?? 0,
      sections: Object.entries(taxonomy.metricsSections ?? {}).map(([id, s]) => ({
        id,
        label: s.label ?? id,
        protocolCount: s.protocolCount ?? 0,
      })),
      sourceEndpoints: meta.sources?.apiEndpoints ?? [],
    };
  },
  ["demo-market"],
  { revalidate: 3600, tags: ["demo-market"] },
);

export async function getMarketSummary(): Promise<MarketSummary | null> {
  return readMarket();
}
