import { ENV_CATALOG } from "./catalog.js";
import type { Environment } from "./types.js";

/**
 * Render the commands that push one environment's values to a platform.
 *
 * The script reads a local dotenv file and pipes each value straight into the platform CLI. That is
 * deliberate: nothing here ever prints a value. A sync tool that echoes secrets to a terminal writes
 * them into shell history, CI logs and scrollback, and the convenience is not worth it — so this
 * emits *instructions that read the file*, and the file stays the caller's responsibility.
 *
 * One target per platform this repo deploys to, so a variable is declared once and lands everywhere
 * it is needed, instead of being re-typed four times and drifting.
 */
export const SYNC_TARGETS = ["dotenv", "vercel", "gcloud", "github"] as const;
export type SyncTarget = (typeof SYNC_TARGETS)[number];

export interface SyncOptions {
  readonly target: SyncTarget;
  readonly environment: Environment;
  /** The local file holding the values for this environment. */
  readonly file: string;
  /** GCP project, for `gcloud`. Falls back to `$GCP_PROJECT`. */
  readonly project?: string;
  /** Push only the variables the catalog marks secret. */
  readonly secretsOnly?: boolean;
}

/** Read from the catalog, so the filter cannot go stale. */
export const SECRET_NAMES: readonly string[] = ENV_CATALOG.filter((spec) => spec.secret).map(
  (spec) => spec.name,
);

/**
 * Vercel's own lane names, which are not ours.
 *
 * This repo has `staging`; Vercel does not. A pull request deploys to *Preview*, and passing `staging`
 * through is not a harmless no-op — the CLI answers "custom environment ids that do not exist: staging"
 * and exits non-zero, so under the generated script's `set -e` the loop dies on the first variable and a
 * sync that appears to have run injects nothing at all.
 */
export const VERCEL_ENVIRONMENTS: Readonly<Record<Environment, string>> = {
  local: "development",
  staging: "preview",
  production: "production",
};

function header(options: SyncOptions): string {
  return [
    "#!/usr/bin/env bash",
    "# Generated by @ethonline2026/env — do not edit.",
    `# target: ${options.target}   environment: ${options.environment}`,
    `# values are read from ${options.file} and piped directly; nothing is echoed`,
    "set -euo pipefail",
    "",
    `FILE="${options.file}"`,
    '[ -f "$FILE" ] || { echo "missing $FILE" >&2; exit 1; }',
    "",
    "while IFS= read -r line; do",
    '  case "$line" in ""|"#"*) continue ;; esac',
    '  key="${line%%=*}"; value="${line#*=}"',
    '  [ -n "$key" ] || continue',
  ].join("\n");
}

function filter(options: SyncOptions): string {
  if (options.secretsOnly !== true) return "";
  const pattern = SECRET_NAMES.length === 0 ? "!*" : SECRET_NAMES.join("|");
  return `  # secrets only\n  case "$key" in ${pattern}) ;; *) continue ;; esac`;
}

function body(options: SyncOptions): string {
  const project = options.project ?? "$GCP_PROJECT";
  switch (options.target) {
    case "dotenv":
      return "  printf '%s=%s\\n' \"$key\" \"$value\"";
    case "vercel": {
      // `vercel env add` reads the value from stdin, so no value reaches the command line or history.
      // --force overwrites an existing key. The empty third argument is the git branch: it is the only
      // spelling of "all Preview branches" that does not open a prompt, and a sync run from CI must
      // never wait for one — without it the CLI reports `git_branch_required` and exits 1.
      const environment = VERCEL_ENVIRONMENTS[options.environment];
      return `  printf '%s' "$value" | vercel env add "$key" ${environment} "" --force --yes --non-interactive`;
    }
    case "gcloud":
      // Update the version when the secret exists, create it when it does not. `versions add` is the
      // only way to change a value: Secret Manager secrets are immutable.
      return [
        `  if gcloud secrets describe "$key" --project ${project} >/dev/null 2>&1; then`,
        `    printf '%s' "$value" | gcloud secrets versions add "$key" --data-file=- --project ${project}`,
        "  else",
        `    printf '%s' "$value" | gcloud secrets create "$key" --data-file=- --replication-policy=automatic --project ${project}`,
        "  fi",
      ].join("\n");
    case "github":
      return `  gh secret set "$key" --env ${options.environment} --body "$value"`;
  }
}

const FOOTER = 'done < "$FILE"\n';

/** Render a runnable script for one target. */
export function renderSyncScript(options: SyncOptions): string {
  return [header(options), filter(options), body(options), FOOTER]
    .filter((part) => part.length > 0)
    .join("\n");
}

/** The names a sync would push, for a dry run that prints no values. */
export function syncPlan(options: {
  readonly service?: string;
  readonly secretsOnly?: boolean;
}): readonly string[] {
  return ENV_CATALOG.filter((spec) => options.service === undefined || spec.services.includes(options.service as never))
    .filter((spec) => options.secretsOnly !== true || spec.secret)
    .map((spec) => spec.name);
}
