// The Agentic EMS scene manifest — v1.2 version updated on 5pt september.
//
// cast model: ONE human — a fixed-income trader on a trading floor,
// doing quant-risk work at their desk. On their desktop runs the Agentic
// EMS with a Copilot; from it they spawn sub-agents that BUILD the screens.
// Each sub-agent's output is a mounted dashboard, not a chat reply. The
// v1.1 four-actor cast collapses into this one person; the agents absorb
// those functions.
//
// These are generated by first: Doing detailed analysis frame by frame of a given video dataset that I have accumulated. In my use case there are two:
// 1. The Bloomberg MS ad
// 2. The example of Vanguard interns that were participating in a trading session
// (vanguard_video/deepagents_agent_manifest.json, gemini-2.5-flash): an
// orchestrator that plans by spinning up specialists; a per-specialist
// panel whose status tag flips; tool calls listed and ticked off green as
// they complete; an overall "X/N completed" progress line; "Working…" with
// an animated ellipsis while active. Ours renames specialists to desks and
// their output is a mounted dashboard.
//
// Every scene follows the FastH3 dense-lane structure:
//   self-contained scene and subject → one camera instruction →
//   soundscape (2–3 clauses) → dialogue with stable speaker tags
// and every scene after the first opens on a described HARD CUT.
//
// Numbers: every numeral quoted in dialogue traces to the scraped
// DeFiLlama snapshot, the tokenised-ETF dashboard, the v1.1 metric lock,
// or a labelled-illustrative anchor group (perps / prediction / governance
// — see app/lib/defillama.ts). Screens are described visually — grids
// assembling, chips lighting, panels mounting — and dialogue carries the
// exact figures, because FastH3 renders speech natively but cannot be
// relied on to draw legible text. Agentic branding throughout; no legacy
// exchange vendor named anywhere.

export interface SceneSpec {
  label: string; // short beat label, shown in the composer + metadata
  prompt: string; // the enqueued text, ≤ 800 chars
  seconds: number; // ≤ 15 s hard cap
}

export const MAX_SCENE_SECONDS = 15;
export const DEFAULT_SCENE_SECONDS = 10;
export const MAX_SCENES = 7;
export const DEFAULT_SCENES = 7;

export const AGENTIC_EPISODE_TITLE = "Agentic EMS v1.2 — The only EMS that will earn qualitative fixed income";

// Voice tags registered once, reused verbatim. One human trader; the deep
// agent is the only other voice on the floor; Marcus joins for Label 7.
const S1 = "S1 (Morgan, the desk's fixed-income trader, low baritone, dry)";
const S5 = "S5 (BB, the deep agent, calm neutral, slightly synthetic)";
const S2 = "S2 (Marcus, head of derivatives, warm baritone)";

export const AGENTIC_EPISODE: { title: string; scenes: SceneSpec[] } = {
  title: AGENTIC_EPISODE_TITLE,
  scenes: [
    {
      label: "01 · 06:30 EST — Floor wakes; the brief to the deep agent",
      seconds: 10,
      prompt:
        `Six-thirty Eastern, London mid-session. A near-black trading floor, one desk, ` +
        `three glowing monitors in razor-sharp 4K. Left: a Hyperliquid perps wall — BTC ` +
        `79,465 red, ETH 2,448.1 red, SOL 101.7, HYPE 83.9, funding and open-interest ` +
        `columns. Centre: a candlestick chart, an amber trend line. Right: the deep agent ` +
        `dock — five desk cards appear in a grid, tagged running, tool ticks green. Slow ` +
        `push-in to her face, focused calm. ${S1}: "Morning sweep — pull the book apart, ` +
        `then simulate basis-carry across the tokenized funds." ${S5}: "Health factor ` +
        `1.42, threshold 1.15. Five specialists running." Soft HVAC bed, low hum, card ` +
        `ticks.`,
    },
    {
      label: "02 · Lending desk mounts; multimodal follow-up",
      seconds: 10,
      prompt:
        `Hard cut to an over-the-shoulder shot of Morgan's centre monitor: the lending ` +
        `desk card flips to complete and its dashboard mounts — a reserve table with rows ` +
        `SPARK 5.18, AAVE 4.20, MORPHO 3.20, utilization and TVL columns, one reserve ` +
        `flagged amber. Morgan drags the amber row toward the deep agent dock with one ` +
        `hand and asks a follow-up out loud, eyes on the screen, brow creasing with alert ` +
        `concern. ${S1}: "This one. What's ` +
        `my duration gap against benchmark?" ${S5}: "Up six basis points. Pulling rate ` +
        `history." Steady key taps, a soft panel-mount whoosh, room tone.`,
    },
    {
      label: "03 · 12:00 EST — The shock; simulation spawned",
      seconds: 10,
      prompt:
        `Hard cut to noon Eastern, a close-up on her face, the risk desk dashboard ` +
        `assembling: key-rate duration strips as violet heat-map rows, a DV01 table ` +
        `beneath, blue shock cards sliding up, a Merton default column beside them. An ` +
        `alert chime — the print, collateral marking down, the health gauge sinking. ` +
        `Morgan goes still, jaw tight, one controlled breath, eyes narrowing. At the dock ` +
        `a simulation card spawns, tool lines ticking — fetch curves, build rate paths, ` +
        `run Monte Carlo. ${S1}: "The print hit. Simulate the defense — ten thousand ` +
        `paths, tokenized funds against the perp hedge." ${S5}: "Simulation sub-agent ` +
        `running." Warning pings, order-book thuds under one held silence.`,
    },
    {
      label: "04 · Perps desk mounts; the sim resolves",
      seconds: 10,
      prompt:
        `Hard cut to a medium shot: the perps desk mounts its Hyperliquid panel — ETH ` +
        `2,448.1 and HYPE 83.9 rows stacking, a funding column reading plus 0.0013 an ` +
        `hour, ten-point-nine APR annualized, open interest two-point-two billion — while ` +
        `the simulation card in the dock resolves into a fan of carry paths spreading ` +
        `across a time axis, its median line settling at one hundred twenty-eight basis ` +
        `points. The trade is detected: Morgan's pupils drop to the median line, a small ` +
        `nod, she leans in and taps the fan. ${S1}: "One-twenty-eight of expected carry. ` +
        `Hedge the delta on the perp." ${S5}: "Hedge sized. Filling on Hyperliquid." ` +
        `Rapid ticks, one low mount tone, the warning bed receding.`,
    },
    {
      label: "05 · Prediction + governance mount; the Ledger gate",
      seconds: 10,
      prompt:
        `Hard cut to a wide shot of the whole desktop: the prediction desk mounts an odds ` +
        `ladder — sixty-two cents on the policy cut, nine cents on a depeg — then the ` +
        `governance desk mounts a vote tracker, proposal SPA-114, a quorum bar filling to ` +
        `eighty-four percent. The deep agent posts a synthesis card: strategy defined, ` +
        `carry inside risk limits, the vote flagged amber. The dock widens into a device-` +
        `confirmation panel — the one irreversible broadcast. Morgan sets her shoulders ` +
        `and presses the hardware button; the badge turns green. ${S5}: "Synthesis ` +
        `locked. Approve the broadcast on device." ${S1}: "Approved. Burn the gas." Two ` +
        `soft mount tones, a single low device click.`,
    },
    {
      label: "06 · Execution; the Web3 celebration",
      seconds: 10,
      prompt:
        `Hard cut to a close-up on her face, screen light on it: the ticket panel fills ` +
        `field by field in amber — repay one hundred fifty million, routed via oneinch, ` +
        `settling on Arc, the FX leg through StableFX — beside the BSM panel, a call at ` +
        `0.4355, a violet vol-skew curve across the strike axis. Her finger clicks green ` +
        `EXECUTE, the compliance badge turns green, the health gauge climbing to 1.38 as ` +
        `the P and L card books the defended carry, and Morgan spins the chair half round, ` +
        `both fists up, laughing at the ceiling. ${S1}: "gm to the print. That's the ` +
        `carry." ${S5}: "Settled on Arc. Carry booked. Memo and audit trail filed." Key ` +
        `clicks, one clean chime, a real laugh.`,
    },
    {
      label: "07 · 17:45 EST — Post-mortem; the observability board before Marcus",
      seconds: 10,
      prompt:
        `Hard cut to 5:45PM Eastern: Marcus, head of derivatives, on the video ` +
        `wall by the observability board — seven runs green, one amber flag, a stale ` +
        `curve fetch. Helene, headset off, walks the board. ${S2}: "The street took a ` +
        `beating. Where was the fault?" ${S1}: "The trace found it — curve ingestion ran ` +
        `eight seconds stale. One rerun fixed it." ${S2}: "Targets?" ${S1}: "Curve fetch ` +
        `under a second, defense extended to flagged votes, Ledger gate on every ` +
        `broadcast." ${S5}: "Lessons filed. Audit trail exported." Low tones, a door ` +
        `clicks shut.`,
    },
  ],
};

// Preset ideas for the composer's idea box, retargeted to the v1.2 arc.
export interface EpisodeIdea {
  title: string;
  idea: string;
}

export const EPISODE_IDEAS: ReadonlyArray<EpisodeIdea> = [
  {
    title: "Agentic EMS v1.2 demo",
    idea:
      "One fixed-income trader on a night floor spawns five sub-agent desks from the " +
      "Agentic EMS copilot — lending, risk, perps, prediction, governance — each building " +
      "a dashboard onto the desktop, ending in one executed ticket and a filed memo",
  },
  {
    title: "Five desks, one print",
    idea:
      "The copilot decomposes a single morning-sweep instruction into five specialist " +
      "desks that mount dashboards around the trader, who steers each one and executes " +
      "on the unified book",
  },
  {
    title: "The vote flag",
    idea:
      "The governance desk flags a proposal touching the book's lending pool mid-sweep, " +
      "and the trader folds it into the risk pass before keying the ticket",
  },
];
